name: build

on: [push, pull_request]

jobs:
  tests:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        python: ["3.7","3.8","3.10","3.11", "pypy-3.7"]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
    - name: Install tox
      run: pip install tox
    - name: Test
      run: tox -e py

  deploy:

    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')

    runs-on: ubuntu-latest

    needs: tests

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.7"
    - name: Install hatch
      run: pip install hatch
    - name: Build package
      run: hatch build
    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.pypi_token }}
